services:
  nextjs:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_AUTH=${NEXT_AUTH}
        - MONGO_URI=${MONGO_URI}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - SESSION_EXPIRE_HOURS=${SESSION_EXPIRE_HOURS}
        - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS}
        - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
        - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
        - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=production
      - PORT=8084
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_AUTH=${NEXT_AUTH}
      - MONGO_URI=${MONGO_URI}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_EXPIRE_HOURS=${SESSION_EXPIRE_HOURS}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s